title: <p style="text-align:center">Johannes <br> Lutzeyer</p>

logo: "https://github.com/johanneslutzeyer/johanneslutzeyer.github.io/blob/main/pictures/JL_profile_picture.jpeg?raw=true"

author: Johannes Lutzeyer


description: >
  <a href="https://scholar.google.com/citations?user=OfT4ns8AAAAJ&hl=en">GoogleScholar</a> <br>
  <a href="https://www.linkedin.com/in/johannes-lutzeyer-213b7480/">LinkedIn</a> <br> 
  <img src="https://github.com/johanneslutzeyer/johanneslutzeyer.github.io/blob/main/pictures/twitter_logo.png?raw=true" alt="Twitter Logo" height="12px"/> <a href="https://twitter.com/jlutzeyer">Twitter</a>
  <br> <br> 
  johannes [dot] lutzeyer [at] polytechnique [dot] edu
  <br> <br> 
  </p>

theme: jekyll-theme-minimal
