title: <p style="text-align:center">Johannes <br> Lutzeyer</p>

logo: "https://github.com/johanneslutzeyer/johanneslutzeyer.github.io/blob/main/pictures/JL_profile_picture.jpeg?raw=true"

author: Johannes Lutzeyer


theme: jekyll-theme-minimal
