title: <p style="text-align:center">Johannes <br> Lutzeyer</p>

logo: "https://github.com/johanneslutzeyer/johanneslutzeyer.github.io/blob/main/pictures/JL_profile_picture.jpeg?raw=true"

author: Johannes Lutzeyer


description: >
  <a href="https://scholar.google.com/citations?user=OfT4ns8AAAAJ&hl=en">GoogleScholar</a> - 
  <a href="https://www.linkedin.com/in/johannes-lutzeyer-213b7480/">LinkedIn</a> - 
  <a href="https://twitter.com/jlutzeyer">Twitter</a>
  <br> <br> 
  johannes [dot] lutzeyer [at] polytechnique [dot] edu
  <br> <br> <br> <br> <br> <br>
  <font size="3"> I would like to sincerely thank Guillaume Salha-Galvan for creating this website and allowing me to copy the format of his website. Guillaume in turn would like to acknowledge the github pages theme by <a href="https://github.com/orderedlist">orderedlist</a></font>.
  </p>

theme: jekyll-theme-minimal
